---
#- name: both os updates
- include: os1.yml
  tags: debian
- include: os2.yml
  tags: redhat
- name: install basic packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - wget
    - curl
    - net-tools
  tags: req_pkgs
- name: Adding group for tomcat
  group:
    name: tomcat
    state: present
  tags: tomcat_group
- name: add the tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
  become: True
  become_method: sudo
  tags: user_creation
- name: download the tomcatfile
  get_url:
    url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    dest: /opt/apache-tomcat-8.5.38.tar.gz
  tags: get_url
- name: extract
  unarchive:
    src: /opt/apache-tomcat-8.5.38.tar.gz
    dest: /opt/
    remote_src: yes
  tags: unzip
- name: Symlink install directory
  file: 
    src: /opt/apache-tomcat-8.5.38
    path: /usr/share/tomcat 
    state: link
  tags: symlink
- name: Change ownership of Tomcat installation
  file: 
    path: /usr/share/tomcat/ 
    owner: tomcat 
    group: tomcat 
    state: directory 
    recurse: yes
  tags: ownership
- name: copy the context.xml file into remote tomcat server specified loction
  copy:
    src: files/context.xml
    dest: /usr/share/tomcat/webapps/host-manager/META-INF/
    owner: tomcat
    group: tomcat
    mode: 0755
    force: yes
    backup: yes
#    recurse: yes
  tags: valuechange1
- name: copy the context.xml file into remote tomcat server specified loction
  copy:
    src: context.xml
    dest: /usr/share/tomcat/webapps/manager/META-INF/
    owner: tomcat
    group: tomcat
    mode: 0755
    force: yes
    backup: yes
#    recurse: yes
  tags: valuechange2
- name: Configure Tomcat server
  template: 
    src: server.xml 
    dest: /usr/share/tomcat/conf/
  notify: restart tomcat
- name: Configure Tomcat users
  template: 
    src: tomcat-users.xml 
    dest: /usr/share/tomcat/conf/
  notify: restart tomcat
  tags: users.xml
- name: Start Tomcat
  service: 
    name: tomcat 
    state: restarted 
    enabled: yes
- name: wait for tomcat to start
  wait_for: port={{http_port}}
