- name: update the centos packages
  shell: yum update -y
  when: ansible_facts['os_family'] == 'RedHat'
  tags: update_os2
- name: install open jdk on centos
  yum:
    name: java-1.8.0-openjdk
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags: installing_openjdk
- name: Install Tomcat init script on centos
  copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat
    mode: 0755
  when: ansible_facts['os_family'] == 'RedHat'
