---
#  environment:
#    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.amzn2.x86_64
#- name: env setup for redhat
#  environment:
#    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
#  when: ansible_facts['os_family'] == 'RedHat'
- name: including debian yaml 
  include: debian.yml
- name: including redhat yaml
  include: redhat.yml
- name: create tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755
    recurse: yes
- name: download the tomcat file
  get_url:
    url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    dest: /opt/tomcat
    mode: 0644
- name: extract
  unarchive:
    src: /opt/tomcat/apache-tomcat-8.5.38.tar.gz
    dest: /opt/tomcat/
    remote_src: yes
    mode: 0777
  ignore_errors: yes
#- name: linking the executable file
#  shell: ln -s /opt/tomcat/apache-tomcat-8.5.38/bin/startup.sh /usr/bin/tomcatup
#- name: linking the executable file for tomcatdown
#  shell: ln -s /opt/tomcat/apache-tomcat-8.5.38/bin/shutdown.sh /usr/bin/tomcatdown
- name: copy the tomcat-users.xml file into remote tomcat server specified loction
  copy:
    src: tomcat-users.xml
    dest: /opt/tomcat/apache-tomcat-8.5.38/conf/
    owner: root
    group: root
    mode: 0755
    force: yes
    backup: yes
  tags: tomcat-users
- name: copy the context.xml file into remote tomcat server specified loction
  copy:
    src: files/context.xml
    dest: /opt/tomcat/apache-tomcat-8.5.38/webapps/host-manager/META-INF/
    owner: root
    group: root
    mode: 0755
    force: yes
    backup: yes
  tags: valuechange1
- name: copy the context.xml file into remote tomcat server specified loction
  copy:
    src: context.xml
    dest: /opt/tomcat/apache-tomcat-8.5.38/webapps/manager/META-INF/
    owner: root
    group: root
    mode: 0755
    force: yes
    backup: yes
  tags: valuechange2
- name: copy the server.xml file into remote tomcat server specified loction
  copy:
    src: server.xml
    dest: /opt/tomcat/apache-tomcat-8.5.38/conf/
    owner: root
    group: root
    mode: 0755
    force: yes
    backup: yes
  tags: valuechange3
- name: including debian service yaml
  include: debian_service.yml
- name: including redhat service yaml
  include: redhat_service.yml
# tasks file for tomcat
